name: python-linter

on: [pull_request]

jobs:
  black:
    strategy:
      matrix:
        python: ["3.10"]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "/src/* /pulumi/*"
          use-black: true
          use-mypy: true
          use-isort: true
